name: Tag master branch
run-name: PR Merge GitHub Actions 🏷️ V1
on: 
  pull_request:
    types: 
      - closed
    branches:
      - 'main'
      
jobs:
  if_merged:
    name: Tag master branch
    if:  github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: one
        with:
          value: "${{ github.ref }})"
          index_of_str: "release/"
          output_name: "releaseVersion"
      #- run: echo "The head of this PR starts with 'release/'"
      #- run: echo "Event Name (${{ github.event_name }}), HeadRef (${{ github.head_ref }}), PR Merged (${{github.event.pull_request.merged}})"
      #- run: echo "RELEASE_VERSION=${github.head_ref/release\//}"
      - run: echo "Tagging master by version - ${{steps.one.outputs.releaseVersion}}"
      - run: |
            git tag -a ${{steps.one.outputs.releaseVersion}} -m "Version ${{steps.one.outputs.releaseVersion}}"
            git push --follow-tags
