name: Tag master branch
run-name: PR Merge GitHub Actions 🏷️
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  if_merged:
    name: Tag master branch
        
    #if:  github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event Name (${{ github.event_name }}), HeadRef (${{ github.head_ref }}), Ref (${{ github.ref }}), PR Merged (${{github.event.pull_request.merged}})"
      - uses: bhowell2/github-substring-action@1.0.2
        id: one
        with:
          value: "${{ github.head_ref }}"
          index_of_str: "release/"
          output_name: "releaseVersion"
      #- run: echo "The head of this PR starts with 'release/'"
      #- run: echo "Event Name (${{ github.event_name }}), HeadRef (${{ github.head_ref }}), PR Merged (${{github.event.pull_request.merged}})"
      #- run: echo "RELEASE_VERSION=${github.head_ref/release\//}"
      - run: echo "Tagging master by version - ${{steps.one.outputs.releaseVersion}}"
      - name: Creating Tag
        uses: actions/checkout@v4
      - run: echo "DKA GITHUB_ACTOR (${GITHUB_ACTOR})"
      - run: echo "Login (${{ github.event.pull_request.user.login }})"
      - run: echo "Email - (${{ github.event.pull_request.user.email }})"
      - run: echo ".user.email - (${{ github.event.pull_request.pull_request.user.email }})"
      - run: echo "github.event.sender.id - ${{github.event.sender.id}}"
      - run: echo "github.event.sender.login - ${{github.event.sender.login}}"
      - run: echo "github.event.sender.login - ${{github.event.sender.login}}"
      - run: git config --global user.name ${{ github.triggering_actor }}
      - run: git config --global user.email ${{ github.event.pusher.email }}
      - name: Create tag
        run: |
          git tag -a v1.1.0 -m "Version 1.0"
          git push --follow-tags
