name: Tag master branch
run-name: PR Merge GitHub Actions 🚀
on: 
  pull_request:
    types: 
      - closed
    branches:
      - 'main'
      
jobs:
  if_merged:
    name: Tag master branch
    if:  github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
    - run: echo "The head of this PR starts with 'release/'"
    - run: echo "Event Name (${{ github.event_name }}), HeadRef (${{ github.head_ref }}), PR Merged (${{github.event.pull_request.merged}})"
    - run: echo "RELEASE_VERSION=${github.head_ref/release\//}"
    - run: echo "Tagging master by $RELEASE_VERSION"
    - run: |
            git tag -a $RELEASE_VERSION -m "Version RELEASE_VERSION"
            git push --follow-tags
