name: PR Merge Demo
run-name: PR Merge GitHub Actions 🚀
on: 
  pull_request:
    types: 
      - closed
    branches:
      - 'main'
      
jobs:
  printData:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The head of this PR starts with 'releases/'"
    - run: echo "Event Name (${{ github.event_name }}), HeadRef (${{ github.head_ref }}), PR Merged (${{github.event.pull_request.merged}})"
  if_merged:
    if:  github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
    - run: echo "The head of this PR starts with 'releases/'"
    - run: echo "Event Name (${{ github.event_name }}), HeadRef (${{ github.event_name }}), PR Merged (${{github.event.pull_request.merged}})"
