name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: rickstaa/action-create-tag@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "DKA_T1"
          tag_exists_error: false
          message: "Created Tag DKA_T1"