name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "DATA - [${{ github.ref }}], [${{steps.one.outputs.releaseVersion}}]"
      - run: echo "Print Version releaseVersion - ${{steps.one.outputs.releaseVersion}}"
      - run: |
          git tag -a DKA_T1 -m "Version T1"
          git push --tags
