name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions T10 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.3.x'
      - name: Create git tag
        run: |
          git tag "DKA_Test_T10"
      - name: Push git tag
        run: git push --tags
