name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps: 
      - uses: bhowell2/github-substring-action@1.0.2
        id: one
        with:
          value: "abc123"
          index_of_str: "ab"
          output_name: "substringData"
      - run: echo "Print- ${steps.one.outputs.substringData}"
