name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/github-script@0.9.0
        id: one
        with:
          script: |
            const id = github.ref.split('/')[1];
            core.setOutput('iddd', id)
      - run: echo "Print- ${{steps.one.outputs.iddd}}"
