name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions T10 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create tag
        run: |
          git tag -a v1.1.0 -m "Version 1.0"
          git push --follow-tags
