name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps: 
      - run: echo "The head of this (${{ github.ref }})"
      - run: echo "BRANCH_PREFIX=refs/heads/release/"
      - run: echo "Branch Prefix - ${BRANCH_PREFIX}"
      - run: echo "RELEASE_VERSION=${github.ref/$BRANCH_PREFIX/ }"
      - run: echo "Version -  $RELEASE_VERSION"
