name: "Workflow example"
on:
  schedule:
    - cron: '*/1 * * * *'
    
jobs:
  find_available_prs:
    runs-on: ubuntu-latest
    steps:
        - name: list all closed pull requests in last 24 hours
          id: list
          uses: actions/github-list-pull-requests@v1.0
          with:
            token: ${{secrets.GITHUB_TOKEN}}
            state: 'closed'
            window: '24'
        - name: output
          run: echo '${{ steps.list.outputs.pullRequestNumbers }}'
